export const Errors = {
  INVALID_CREDENTIALS: "Invalid email or password",
  UNAUTHORIZED: "Unauthorized",
  FORBIDDEN: "Forbidden",
  TOKEN_EXPIRED: "Token expired",
  TOKEN_INVALID: "Invalid token",
  REFRESH_REVOKED: "Refresh token revoked",
  USER_NOT_FOUND: "User not found",
  EMAIL_ALREADY_EXISTS: "Email already exists",
  EMAIL_NOT_VERIFIED: "Email not verified",
  EMAIL_ALREADY_VERIFIED: "Email already verified",
  VERIFICATION_TOKEN_EXPIRED: "Verification token expired",
  VERIFICATION_TOKEN_INVALID: "Invalid verification token",
  RESET_TOKEN_EXPIRED: "Reset token expired",
  RESET_TOKEN_INVALID: "Invalid reset token",
  RESET_TOKEN_ALREADY_USED: "Reset token already used",
  INVALID_EMAIL_FORMAT: "Invalid email format",
  PASSWORD_TOO_SHORT: "Password must be at least 6 characters",
  OAUTH_FLOW_FAILED: "OAuth authentication failed",
  OAUTH_ACCOUNT_LINKING_FAILED: "Failed to link OAuth account",
};
